"""Presentation-ready clean multi-robot warehouse demo."""

from __future__ import annotations

from dataclasses import dataclass
from math import atan2, cos, hypot, sin
from pathlib import Path

import imageio.v2 as imageio
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation

from warehouse_planning.config import ScenarioConfig
from warehouse_planning.models.dynamic_obstacle import DynamicObstacle
from warehouse_planning.models.robot import Robot
from warehouse_planning.models.robot import RobotState
from warehouse_planning.planning.collision import CollisionChecker
from warehouse_planning.planning.kinodynamic_astar import (
    ContinuousPose,
    KinodynamicAStarPlanner,
)
from warehouse_planning.visualization.plotting import ROBOT_COLORS, WarehousePlotter
from warehouse_planning.visualization.smoothing import (
    interpolate_path,
    pose_at_time,
)


@dataclass(frozen=True)
class CleanDemoOutputs:
    """Output files generated by the clean demo."""

    clean_map_png: Path
    risk_field_png: Path
    mp4_path: Path | None
    gif_path: Path | None


def run_clean_multi_robot_demo(
    scenario: ScenarioConfig,
    results_dir: str | Path,
    show: bool = True,
    fps: int = 12,
    duration: float | None = None,
    save_gif: bool = False,
) -> CleanDemoOutputs:
    """Run and save the clean multi-robot presentation demo."""
    output_dir = Path(results_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    duration = duration or scenario.simulation.horizon
    plotter = WarehousePlotter(style="clean")

    smooth_paths = plan_and_smooth_demo_paths(scenario)
    pedestrian_paths = generate_pedestrian_paths(
        scenario,
        duration=duration,
        dt=min(0.1, scenario.simulation.dt),
    )

    clean_map_png = output_dir / "clean_map_demo.png"
    risk_field_png = output_dir / "risk_field_demo.png"
    mp4_path = output_dir / "multi_robot_demo.mp4"
    gif_path = output_dir / "multi_robot_demo.gif" if save_gif else None

    clean_fig, clean_ax = plt.subplots(figsize=(12, 8), facecolor="white")
    draw_clean_demo_frame(
        clean_ax,
        scenario,
        smooth_paths,
        pedestrian_paths,
        time=0.0,
        show_risk=False,
        plotter=plotter,
    )
    clean_fig.savefig(clean_map_png, dpi=170, bbox_inches="tight", pad_inches=0.05)
    plt.close(clean_fig)

    risk_fig, risk_ax = plt.subplots(figsize=(12, 8), facecolor="white")
    draw_clean_demo_frame(
        risk_ax,
        scenario,
        smooth_paths,
        pedestrian_paths,
        time=min(duration * 0.45, scenario.simulation.horizon),
        show_risk=True,
        plotter=plotter,
    )
    risk_fig.savefig(risk_field_png, dpi=170, bbox_inches="tight", pad_inches=0.05)
    plt.close(risk_fig)

    frame_times = np.linspace(0.0, duration, max(2, int(duration * fps)))
    frames = [
        render_clean_demo_frame(
            scenario,
            smooth_paths,
            pedestrian_paths,
            float(time),
            show_risk=False,
        )
        for time in frame_times
    ]

    saved_mp4: Path | None = None
    try:
        imageio.mimsave(mp4_path, frames, fps=fps)
        saved_mp4 = mp4_path
    except Exception:
        saved_mp4 = None

    saved_gif: Path | None = None
    if save_gif or saved_mp4 is None:
        fallback_gif = gif_path or output_dir / "multi_robot_demo.gif"
        imageio.mimsave(fallback_gif, frames, duration=1000 / fps)
        saved_gif = fallback_gif

    if show:
        fig, ax = plt.subplots(figsize=(12, 8), facecolor="white")

        def update(frame_time: float) -> None:
            draw_clean_demo_frame(
                ax,
                scenario,
                smooth_paths,
                pedestrian_paths,
                time=frame_time,
                show_risk=False,
                plotter=plotter,
            )

        animation = FuncAnimation(
            fig,
            update,
            frames=frame_times,
            interval=1000 / fps,
            repeat=True,
        )
        animation.event_source.start()
        plt.show()

    return CleanDemoOutputs(
        clean_map_png=clean_map_png,
        risk_field_png=risk_field_png,
        mp4_path=saved_mp4,
        gif_path=saved_gif,
    )


def plan_and_smooth_demo_paths(
    scenario: ScenarioConfig,
    samples_per_segment: int = 10,
) -> dict[str, list[ContinuousPose]]:
    """Plan coarse paths with A* and smooth them for visualization."""
    coarse_paths = plan_demo_paths(scenario)
    smooth_paths = {
        robot_id: interpolate_path(path, samples_per_segment=samples_per_segment)
        for robot_id, path in coarse_paths.items()
    }
    return apply_priority_timing_avoidance(smooth_paths, scenario)


def plan_demo_paths(scenario: ScenarioConfig) -> dict[str, list[ContinuousPose]]:
    """Plan one coarse path per robot using the existing kinodynamic A* pipeline."""
    collision_checker = CollisionChecker(warehouse=scenario.warehouse)
    planner = KinodynamicAStarPlanner(
        collision_checker=collision_checker,
        dt=scenario.simulation.dt,
        theta_bins=32,
        step_distance=0.5,
        goal_tolerance=0.65,
        max_time_steps=int(scenario.simulation.horizon / scenario.simulation.dt),
        risk_weight=0.0,
    )

    paths: dict[str, list[ContinuousPose]] = {}
    for robot in scenario.robots:
        try:
            paths[robot.id] = planner.plan(robot)
        except ValueError:
            paths[robot.id] = make_aisle_fallback_path(robot, scenario)
    return paths


def make_aisle_fallback_path(
    robot: Robot,
    scenario: ScenarioConfig,
    speed: float = 1.25,
) -> list[ContinuousPose]:
    """Create a simple Dubins-like aisle route when lattice planning fails."""
    route_y = scenario.warehouse.height * 0.5
    waypoints = [
        (robot.start.x, robot.start.y),
        (robot.start.x, route_y),
        (robot.goal.x, route_y),
        (robot.goal.x, robot.goal.y),
    ]
    compact_waypoints = [waypoints[0]]
    for waypoint in waypoints[1:]:
        if hypot(
            waypoint[0] - compact_waypoints[-1][0],
            waypoint[1] - compact_waypoints[-1][1],
        ) > 1e-6:
            compact_waypoints.append(waypoint)

    poses: list[ContinuousPose] = []
    current_time = 0.0
    for index, waypoint in enumerate(compact_waypoints):
        if index < len(compact_waypoints) - 1:
            next_waypoint = compact_waypoints[index + 1]
            theta = atan2(next_waypoint[1] - waypoint[1], next_waypoint[0] - waypoint[0])
        elif poses:
            theta = poses[-1][2]
        else:
            theta = robot.start.theta

        if index > 0:
            previous = compact_waypoints[index - 1]
            current_time += hypot(waypoint[0] - previous[0], waypoint[1] - previous[1]) / speed
        poses.append((waypoint[0], waypoint[1], theta, current_time))

    return poses


def apply_priority_timing_avoidance(
    paths: dict[str, list[ContinuousPose]],
    scenario: ScenarioConfig,
    time_step: float = 0.1,
    delay_step: float = 0.6,
    max_delay: float = 18.0,
    clearance_margin: float = 0.16,
) -> dict[str, list[ContinuousPose]]:
    """Delay lower-priority robots until they do not overlap earlier robots."""
    scheduled: dict[str, list[ContinuousPose]] = {}
    robot_by_id = {robot.id: robot for robot in scenario.robots}
    for robot in scenario.robots:
        base_path = paths.get(robot.id, [])
        delay = 0.0
        candidate = shift_path_time(base_path, delay)
        while delay <= max_delay:
            candidate = shift_path_time(base_path, delay)
            if not path_conflicts_with_scheduled(
                candidate,
                robot,
                scheduled,
                robot_by_id,
                time_step=time_step,
                clearance_margin=clearance_margin,
            ):
                break
            delay += delay_step
        scheduled[robot.id] = candidate
    return scheduled


def shift_path_time(
    path: list[ContinuousPose],
    delay: float,
) -> list[ContinuousPose]:
    """Shift a path in time while preserving its geometry."""
    return [(x, y, theta, t + delay) for x, y, theta, t in path]


def path_conflicts_with_scheduled(
    candidate_path: list[ContinuousPose],
    robot: Robot,
    scheduled_paths: dict[str, list[ContinuousPose]],
    robot_by_id: dict[str, Robot],
    time_step: float,
    clearance_margin: float,
) -> bool:
    """Return whether a candidate path overlaps any already scheduled robot."""
    if not candidate_path:
        return False
    latest_time = max(
        [candidate_path[-1][3]]
        + [path[-1][3] for path in scheduled_paths.values() if path]
    )
    for time in np.arange(0.0, latest_time + time_step, time_step):
        pose = pose_at_time(candidate_path, float(time))
        if pose is None:
            continue
        for other_id, other_path in scheduled_paths.items():
            other_pose = pose_at_time(other_path, float(time))
            if other_pose is None:
                continue
            other_robot = robot_by_id[other_id]
            clearance = robot.radius + other_robot.radius + clearance_margin
            if hypot(pose[0] - other_pose[0], pose[1] - other_pose[1]) < clearance:
                return True
    return False


def generate_pedestrian_paths(
    scenario: ScenarioConfig,
    duration: float,
    dt: float = 0.1,
) -> dict[str, list[ContinuousPose]]:
    """Generate obstacle-aware pedestrian motion with deterministic bouncing."""
    checker = CollisionChecker(warehouse=scenario.warehouse)
    pedestrian_paths: dict[str, list[ContinuousPose]] = {}
    for index, pedestrian in enumerate(scenario.dynamic_obstacles):
        pedestrian_paths[pedestrian.id] = _rollout_pedestrian(
            pedestrian,
            scenario,
            checker,
            duration=duration,
            dt=dt,
            index=index,
        )
    return pedestrian_paths


def pedestrian_positions_at_time(
    pedestrian_paths: dict[str, list[ContinuousPose]],
    time: float,
) -> dict[str, tuple[float, float]]:
    """Return current pedestrian positions from rollout paths."""
    positions: dict[str, tuple[float, float]] = {}
    for pedestrian_id, path in pedestrian_paths.items():
        pose = pose_at_time(path, time)
        if pose is not None:
            positions[pedestrian_id] = (pose[0], pose[1])
    return positions


def _rollout_pedestrian(
    pedestrian: DynamicObstacle,
    scenario: ScenarioConfig,
    checker: CollisionChecker,
    duration: float,
    dt: float,
    index: int,
) -> list[ContinuousPose]:
    """Roll one pedestrian forward while avoiding walls and shelves."""
    waypoints = [(point[1], point[2]) for point in pedestrian.trajectory]
    x, y = waypoints[0]
    target_index = 1 if len(waypoints) > 1 else 0
    speed = 0.45 + 0.07 * (index % 4)
    heading = 0.0
    path: list[ContinuousPose] = [(x, y, heading, 0.0)]

    for step in range(1, int(duration / dt) + 1):
        time = step * dt
        target = waypoints[target_index]
        if hypot(target[0] - x, target[1] - y) < 0.35 and len(waypoints) > 1:
            target_index = (target_index + 1) % len(waypoints)
            target = waypoints[target_index]

        base_heading = atan2(target[1] - y, target[0] - x)
        wobble = 0.45 * sin(0.8 * time + index * 1.7) + 0.18 * sin(1.9 * time + index)
        heading = base_heading + wobble
        dx = speed * cos(heading) * dt
        dy = speed * sin(heading) * dt
        next_x, next_y, heading = _valid_pedestrian_step(
            x,
            y,
            dx,
            dy,
            heading,
            pedestrian,
            checker,
            scenario,
        )
        x, y = next_x, next_y
        path.append((x, y, heading, time))
    return path


def _valid_pedestrian_step(
    x: float,
    y: float,
    dx: float,
    dy: float,
    heading: float,
    pedestrian: DynamicObstacle,
    checker: CollisionChecker,
    scenario: ScenarioConfig,
) -> tuple[float, float, float]:
    """Accept, bounce, or stop a pedestrian step before obstacle collision."""
    candidates = (
        (dx, dy, heading),
        (-dx, dy, atan2(dy, -dx)),
        (dx, -dy, atan2(-dy, dx)),
        (-dx, -dy, atan2(-dy, -dx)),
        (dy, -dx, atan2(-dx, dy)),
        (-dy, dx, atan2(dx, -dy)),
    )
    for candidate_dx, candidate_dy, candidate_heading in candidates:
        candidate_x = x + candidate_dx
        candidate_y = y + candidate_dy
        state = RobotState(candidate_x, candidate_y, candidate_heading, pedestrian.radius)
        if not checker.collides_with_static_obstacle(state):
            return (candidate_x, candidate_y, candidate_heading)

    clamped_x = min(
        scenario.warehouse.width - pedestrian.radius,
        max(pedestrian.radius, x),
    )
    clamped_y = min(
        scenario.warehouse.height - pedestrian.radius,
        max(pedestrian.radius, y),
    )
    return (clamped_x, clamped_y, heading)


def draw_clean_demo_frame(
    ax,
    scenario: ScenarioConfig,
    smooth_paths: dict[str, list[ContinuousPose]],
    pedestrian_paths: dict[str, list[ContinuousPose]],
    time: float,
    show_risk: bool,
    plotter: WarehousePlotter | None = None,
) -> None:
    """Draw one clean demo frame on an existing axis."""
    plotter = plotter or WarehousePlotter(style="clean")
    ax.clear()
    plotter.configure_clean_axis(ax, scenario)
    pedestrian_positions = pedestrian_positions_at_time(pedestrian_paths, time)
    if show_risk:
        plotter.draw_risk_field(
            ax,
            scenario,
            time=time,
            pedestrian_positions=pedestrian_positions,
        )
    plotter.draw_clean_obstacles(ax, scenario)

    for robot_index, robot in enumerate(scenario.robots):
        color = ROBOT_COLORS[robot_index % len(ROBOT_COLORS)]
        ax.plot(
            robot.goal.x,
            robot.goal.y,
            marker="x",
            color=color,
            markersize=7,
            markeredgewidth=1.8,
            alpha=0.55,
            zorder=3,
        )
        path = smooth_paths.get(robot.id, [])
        plotter.draw_robot_motion(
            ax,
            path,
            time=time,
            color=color,
            radius=robot.radius,
        )

    plotter.draw_pedestrians(
        ax,
        scenario,
        time=time,
        pedestrian_positions=pedestrian_positions,
    )


def render_clean_demo_frame(
    scenario: ScenarioConfig,
    smooth_paths: dict[str, list[ContinuousPose]],
    pedestrian_paths: dict[str, list[ContinuousPose]],
    time: float,
    show_risk: bool,
) -> np.ndarray:
    """Render one clean demo frame as an RGB image array."""
    fig, ax = plt.subplots(figsize=(12, 8), facecolor="white")
    draw_clean_demo_frame(
        ax,
        scenario,
        smooth_paths,
        pedestrian_paths,
        time=time,
        show_risk=show_risk,
    )
    fig.canvas.draw()
    width, height = fig.canvas.get_width_height()
    rgba = np.frombuffer(fig.canvas.buffer_rgba(), dtype=np.uint8)
    frame = rgba.reshape((height, width, 4))[:, :, :3].copy()
    plt.close(fig)
    return frame
